version: '3.9'
services:
  opensearch:
    image: opensearchproject/opensearch:3.0.0
    container_name: opensearch-geoip-fixed
    environment:
      # Basic settings
      discovery.type: single-node
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 0AkkUKg0Fe+H
      bootstrap.memory_lock: false
      OPENSEARCH_JAVA_OPTS: -Xms1g -Xmx1g
      # Security settings for HTTPS
      plugins.security.ssl.transport.pemcert_filepath: esnode.pem
      plugins.security.ssl.transport.pemkey_filepath: esnode-key.pem
      plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
      plugins.security.ssl.transport.enforce_hostname_verification: false
      plugins.security.ssl.http.enabled: true
      plugins.security.ssl.http.pemcert_filepath: esnode.pem
      plugins.security.ssl.http.pemkey_filepath: esnode-key.pem
      plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem
      plugins.security.allow_unsafe_democertificates: true
      plugins.security.allow_default_init_securityindex: true
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      # Mount GeoIP databases to standard location
      - /home/meet/Documents/geoip-poc/geoip-databases:/usr/share/opensearch/geoip-databases:ro
      # Persist data
      - opensearch-data:/usr/share/opensearch/data
    restart: unless-stopped

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      # 👇 FIXED: Use HTTPS and add credentials
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: your_password     # Update Your Password
      # 👇 Allow self-signed certificates
      OPENSEARCH_SSL_VERIFICATIONMODE: none
    depends_on:
      - opensearch
    restart: unless-stopped

volumes:
  opensearch-data:
